//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaasNet.StateMachine.Runtime.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FaasNet.StateMachine.Runtime.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à an event cannot be added to an active state.
        /// </summary>
        internal static string AddEventToActiveState {
            get {
                return ResourceManager.GetString("AddEventToActiveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the RestApi URL {0} doesn&apos;t match the format : url#operationid.
        /// </summary>
        internal static string BadRESTApiUrl {
            get {
                return ResourceManager.GetString("BadRESTApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à state machine instance with status &apos;{0}&apos; cannot be reactivated.
        /// </summary>
        internal static string CannotReactivateStateMachineInstance {
            get {
                return ResourceManager.GetString("CannotReactivateStateMachineInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the input {0} is not a valid array.
        /// </summary>
        internal static string InvalidArrayInput {
            get {
                return ResourceManager.GetString("InvalidArrayInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the asyncapi URL {0} is invalid.
        /// </summary>
        internal static string InvalidAsyncApiUrl {
            get {
                return ResourceManager.GetString("InvalidAsyncApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the input {0} is not a valid object.
        /// </summary>
        internal static string InvalidObjectInput {
            get {
                return ResourceManager.GetString("InvalidObjectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the input {0} is not a valid string.
        /// </summary>
        internal static string InvalidStringInput {
            get {
                return ResourceManager.GetString("InvalidStringInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à at least one OnEvent must be specified.
        /// </summary>
        internal static string MissingOnEvents {
            get {
                return ResourceManager.GetString("MissingOnEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the parameter {0} is missing from the input.
        /// </summary>
        internal static string MissingPropertyFromInput {
            get {
                return ResourceManager.GetString("MissingPropertyFromInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the parameters {0} are missing.
        /// </summary>
        internal static string MissingRequiredParameters {
            get {
                return ResourceManager.GetString("MissingRequiredParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the content-type exposed by the operation {0} are not supported.
        /// </summary>
        internal static string NoContentTypeSupportedInOperation {
            get {
                return ResourceManager.GetString("NoContentTypeSupportedInOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no schema attribute is specified in the operation {0}.
        /// </summary>
        internal static string NoSchemaSpecifiedInContentType {
            get {
                return ResourceManager.GetString("NoSchemaSpecifiedInContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the ASYNCAPI operation {0} doesn&apos;t exist.
        /// </summary>
        internal static string UnknownAsyncAPIOperation {
            get {
                return ResourceManager.GetString("UnknownAsyncAPIOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à there is no processor for the function {0}.
        /// </summary>
        internal static string UnknownFunctionProcessor {
            get {
                return ResourceManager.GetString("UnknownFunctionProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the HTTP operation {0} doesn&apos;t exist.
        /// </summary>
        internal static string UnknownHttpAPIOperation {
            get {
                return ResourceManager.GetString("UnknownHttpAPIOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the OpenAPI operation {0} doesn&apos;t exist.
        /// </summary>
        internal static string UnknownOpenAPIOperation {
            get {
                return ResourceManager.GetString("UnknownOpenAPIOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the schema {0} doesn&apos;t exist.
        /// </summary>
        internal static string UnknownSchema {
            get {
                return ResourceManager.GetString("UnknownSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the workflow definition {0} doesn&apos;t exist.
        /// </summary>
        internal static string UnknownWorkflowDefinition {
            get {
                return ResourceManager.GetString("UnknownWorkflowDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the workflow state {0} doesn&apos;t exist.
        /// </summary>
        internal static string UnknownWorkflowState {
            get {
                return ResourceManager.GetString("UnknownWorkflowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the in parameter type {0} is not supported.
        /// </summary>
        internal static string UnsupportedInParameter {
            get {
                return ResourceManager.GetString("UnsupportedInParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the OPENAPI version is not supported.
        /// </summary>
        internal static string UnsupportedOpenApiVersion {
            get {
                return ResourceManager.GetString("UnsupportedOpenApiVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no protocol is supported.
        /// </summary>
        internal static string UnsupportedProtocol {
            get {
                return ResourceManager.GetString("UnsupportedProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the security scheme {0} is not supported.
        /// </summary>
        internal static string UnsupportedSecurityScheme {
            get {
                return ResourceManager.GetString("UnsupportedSecurityScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the type {0} is not supported.
        /// </summary>
        internal static string UnsupportedType {
            get {
                return ResourceManager.GetString("UnsupportedType", resourceCulture);
            }
        }
    }
}
