// <auto-generated />
using System;
using FaasNet.EventMesh.Runtime.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FaasNet.EventMesh.Runtime.Website.Migrations
{
    [DbContext(typeof(EventMeshDBContext))]
    [Migration("20220317124424_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.ApplicationDomain", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RootTopic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VpnName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VpnName");

                    b.ToTable("ApplicationDomain");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.BridgeServer", b =>
                {
                    b.Property<string>("Urn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Vpn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VpnName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Urn");

                    b.HasIndex("VpnName");

                    b.ToTable("BridgeServer");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.BrokerConfiguration", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Protocol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("BrokerConfigurations");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.BrokerConfigurationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrokerConfigurationName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrokerConfigurationName");

                    b.ToTable("BrokerConfigurationRecord");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purposes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Urn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VpnName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClientId");

                    b.HasIndex("VpnName");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.ClientSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BufferCloudEvents")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Environment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("IPAddressData")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Pid")
                        .HasColumnType("int");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<int>("PurposeCode")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Vpn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientSession");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.ClientSessionBridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientSessionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Urn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vpn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientSessionId");

                    b.ToTable("ClientSessionBridge");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.ClientSessionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientSessionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientSessionId");

                    b.ToTable("ClientSessionHistory");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.ClientSessionPendingCloudEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrokerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSessionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("EvtPayload")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientSessionId");

                    b.ToTable("ClientSessionPendingCloudEvent");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrokerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSessionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientSessionId");

                    b.ToTable("Topic");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Topic");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.Vpn", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Name");

                    b.ToTable("VpnLst");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.ClientTopic", b =>
                {
                    b.HasBaseType("FaasNet.EventMesh.Runtime.Models.Topic");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Offset")
                        .HasColumnType("int");

                    b.HasIndex("ClientId");

                    b.HasDiscriminator().HasValue("ClientTopic");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.ApplicationDomain", b =>
                {
                    b.HasOne("FaasNet.EventMesh.Runtime.Models.Vpn", null)
                        .WithMany("ApplicationDomains")
                        .HasForeignKey("VpnName")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.BridgeServer", b =>
                {
                    b.HasOne("FaasNet.EventMesh.Runtime.Models.Vpn", null)
                        .WithMany("BridgeServers")
                        .HasForeignKey("VpnName")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.BrokerConfigurationRecord", b =>
                {
                    b.HasOne("FaasNet.EventMesh.Runtime.Models.BrokerConfiguration", null)
                        .WithMany("Records")
                        .HasForeignKey("BrokerConfigurationName")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.Client", b =>
                {
                    b.HasOne("FaasNet.EventMesh.Runtime.Models.Vpn", null)
                        .WithMany("Clients")
                        .HasForeignKey("VpnName")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.ClientSession", b =>
                {
                    b.HasOne("FaasNet.EventMesh.Runtime.Models.Client", null)
                        .WithMany("Sessions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.ClientSessionBridge", b =>
                {
                    b.HasOne("FaasNet.EventMesh.Runtime.Models.ClientSession", null)
                        .WithMany("Bridges")
                        .HasForeignKey("ClientSessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.ClientSessionHistory", b =>
                {
                    b.HasOne("FaasNet.EventMesh.Runtime.Models.ClientSession", null)
                        .WithMany("Histories")
                        .HasForeignKey("ClientSessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.ClientSessionPendingCloudEvent", b =>
                {
                    b.HasOne("FaasNet.EventMesh.Runtime.Models.ClientSession", null)
                        .WithMany("PendingCloudEvents")
                        .HasForeignKey("ClientSessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.Topic", b =>
                {
                    b.HasOne("FaasNet.EventMesh.Runtime.Models.ClientSession", null)
                        .WithMany("Topics")
                        .HasForeignKey("ClientSessionId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.ClientTopic", b =>
                {
                    b.HasOne("FaasNet.EventMesh.Runtime.Models.Client", null)
                        .WithMany("Topics")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.BrokerConfiguration", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.Client", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.ClientSession", b =>
                {
                    b.Navigation("Bridges");

                    b.Navigation("Histories");

                    b.Navigation("PendingCloudEvents");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Runtime.Models.Vpn", b =>
                {
                    b.Navigation("ApplicationDomains");

                    b.Navigation("BridgeServers");

                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
