version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2022
nuget:
  disable_publish_on_pr: true
install:
  - git submodule update --init --recursive
build_script:
- cmd: >-
    .\psake.cmd ci


    7z a EventMeshCLI.zip .\build\results\eventMeshCLI\*


    7z a EventMeshService.zip .\build\results\eventMeshService\*


    7z a EventMeshProtocolsAMQP.zip .\build\results\protocolPlugins\FaasNet.EventMesh.Protocols.AMQP\*


    7z a EventMeshProtocolsWebsocket.zip .\build\results\protocolPlugins\FaasNet.EventMesh.Protocols.WebSocket\*


    7z a EventMeshSinksAMQP.zip .\build\results\sinkPlugins\FaasNet.EventMesh.Sink.AMQP\*


    7z a EventMeshSinksKafka.zip .\build\results\sinkPlugins\FaasNet.EventMesh.Sink.Kafka\*


    7z a EventMeshSinksVpnBridge.zip .\build\results\sinkPlugins\FaasNet.EventMesh.Sink.VpnBridge\*


    7z a EventMeshDiscoveryConfig.zip .\build\results\discoveryPlugins\FaasNet.RaftConsensus.Discovery.Config


    7z a EventMeshDiscoveryEtcd.zip .\build\results\discoveryPlugins\FaasNet.RaftConsensus.Discovery.Etcd
test: off
artifacts:
- path: EventMeshCLI.zip
  name: EventMeshCLI.zip
- path: EventMeshService.zip
  name: EventMeshService.zip
- path: EventMeshProtocolsAMQP.zip
  name: EventMeshProtocolsAMQP.zip
- path: EventMeshProtocolsWebsocket.zip
  name: EventMeshProtocolsWebsocket.zip
- path: EventMeshSinksAMQP.zip
  name: EventMeshSinksAMQP.zip
- path: EventMeshSinksKafka.zip
  name: EventMeshSinksKafka.zip
- path: EventMeshSinksVpnBridge.zip
  name: EventMeshSinksVpnBridge.zip
- path: EventMeshDiscoveryConfig.zip
  name: EventMeshDiscoveryConfig.zip
- path: EventMeshDiscoveryEtcd.zip
  name: EventMeshDiscoveryEtcd.zip
deploy:
- provider: GitHub
  auth_token:
    secure: +U/L+mprfN3zjYnRB3B4oCdZlfGAiHv1hnVZZglvDQj0Mew4Y2I5BQoCli8hJd6u
  artifact: /.*\.zip/
  on:
    branch: master
    appveyor_repo_tag: true