import { createAction, props } from '@ngrx/store';
import { PrometheusQueryRangeResult, PrometheusQueryResult } from '../../common/prometheus-query.model';
import { SearchResult } from '../../common/search.model';
import { FunctionDetailsResult } from '../models/function-details.model';
import { FunctionResult } from '../models/function.model';

export const startSearch = createAction('[Functions] START_SEARCH_FUNCTIONS', props<{ order: string, direction: string, count: number, startIndex: number }>());
export const completeSearch = createAction('[Functions] COMPLETE_SEARCH_FUNCTIONS', props<{ content: SearchResult<FunctionResult> }>());
export const errorSearch = createAction('[Functions] ERROR_SEARCH_FUNCTIONS');
export const startGetConfiguration = createAction('[Functions] START_GET_FUNCTION_CONFIGURATION', props<{ name: string }>());
export const completeGetConfiguration = createAction('[Functions] COMPLETE_GET_FUNCTION_CONFIGURATION', props<{ content: any }>());
export const errorGetConfiguration = createAction('[Functions] ERROR_GET_FUNCTION_CONFIGURATION');
export const startInvoke = createAction('[Functions] START_INVOKE_FUNCTION', props<{ name: string, request: any }>());
export const completeInvoke = createAction('[Functions] COMPLETE_INVOKE_FUNCTION', props<{ content: any }>());
export const errorInvoke = createAction('[Functions] ERROR_INVOKE_FUNCTION');
export const startGet = createAction('[Functions] START_GET_FUNCTION', props<{ name: string }>());
export const completeGet = createAction('[Functions] COMPLETE_GET_FUNCTION', props<{ content: FunctionResult}>());
export const errorGet = createAction('[Functions] ERROR_GET_FUNCTION');
export const startDelete = createAction('[Functions] START_DELETE_FUNCTION', props<{ name: string }>());
export const completeDelete = createAction('[Functions] COMPLETE_DELETE_FUNCTION');
export const errorDelete = createAction('[Functions] ERROR_DELETE_FUNCTION');
export const startAdd = createAction('[Functions] START_ADD_FUNCTION', props<{ name: string, description: string, image: string, version: string }>());
export const completeAdd = createAction('[Functions] COMPLETE_ADD_FUNCTION', props<{ name: string, description: string, image: string, version : string }>());
export const errorAdd = createAction('[Functions] ERROR_ADD_FUNCTION');
export const startGetThreads = createAction("[Functions] START_GET_THREADS", props<{ name: string, startDate: number, endDate: number }>());
export const completeGetThreads = createAction("[Functions] COMPLETE_GET_THREADS", props<{ content: PrometheusQueryRangeResult }>());
export const errorGetThreads = createAction("[Functions] ERROR_GET_THREADS");
export const startGetVirtualMemoryBytes = createAction("[Functions] START_GET_VIRTUAL_MEMORYBYTES", props<{ name: string, startDate: number, endDate: number }>());
export const completeGetVirtualMemoryBytes = createAction("[Functions] COMPLETE_GET_VIRTUAL_MEMORYBYTES", props<{ content: PrometheusQueryRangeResult }>());
export const errorGetVirtualMemoryBytes = createAction("[Functions] ERROR_GET_VIRTUAL_MEMORYBYTES");
export const startGetCpuUsage = createAction("[Functions] START_GET_CPU_USAGE", props<{ name: string, startDate: number, endDate: number, duration: number }>());
export const completeGetCpuUsage = createAction("[Functions] COMPLETE_GET_CPU_USAGE", props<{ content: PrometheusQueryRangeResult }>());
export const errorGetCpuUsage = createAction("[Functions] ERROR_GET_CPU_USAGE");
export const startGetRequestDuration = createAction("[Functions] START_GET_REQUEST_DURATION", props<{ name: string, startDate: number, endDate: number, duration: number }>());
export const completeGetRequestDuration = createAction("[Functions] COMPLETE_GET_REQUEST_DURATION", props<{ content: PrometheusQueryRangeResult }>());
export const errorGetRequestDuration = createAction("[Functions] ERROR_GET_REQUEST_DURATION");
export const startGetDetails = createAction("[Functions] START_GET_DETAILS", props<{ name: string }>());
export const completeGetDetails = createAction("[Functions] COMPLETE_GET_DETAILS", props<{ content: FunctionDetailsResult }>());
export const errorGetDetails = createAction("[Functions] ERROR_GET_DETAILS");
export const startGetTotalRequests = createAction("[Functions] START_GET_TOTAL_REQUESTS", props<{ name: string, time: number }>());
export const completeGetTotalRequests = createAction("[Functions] COMPLETE_GET_TOTAL_REQUESTS", props<{ content: PrometheusQueryResult }>());
export const errorGetTotalRequests = createAction("[Functions] ERROR_GET_TOTAL_REQUESTS");

