FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /App
COPY . .
RUN dotnet restore
RUN dotnet publish -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /App
ENV ASPNETCORE_URLS=http://*:8080
EXPOSE 8080
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "{{ProjectName}}.dll"]