//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaasNet.Runtime.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FaasNet.Runtime.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the RestApi URL {0} doesn&apos;t match the format : url#operationid.
        /// </summary>
        internal static string BadRESTApiUrl {
            get {
                return ResourceManager.GetString("BadRESTApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the parameters {0} are missing.
        /// </summary>
        internal static string MissingRequiredParameters {
            get {
                return ResourceManager.GetString("MissingRequiredParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no processor for the function {0}.
        /// </summary>
        internal static string UnknownFunctionProcessor {
            get {
                return ResourceManager.GetString("UnknownFunctionProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the OpenAPI operation {0} doesn&apos;t exist.
        /// </summary>
        internal static string UnknownOpenAPIOperation {
            get {
                return ResourceManager.GetString("UnknownOpenAPIOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the workflow definition {0} doesn&apos;t exist.
        /// </summary>
        internal static string UnknownWorkflowDefinition {
            get {
                return ResourceManager.GetString("UnknownWorkflowDefinition", resourceCulture);
            }
        }
    }
}
