//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaasNet.Gateway.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FaasNet.Gateway.Core.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function &apos;{0}&apos; already exists.
        /// </summary>
        internal static string FunctionExists {
            get {
                return ResourceManager.GetString("FunctionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a function with the name &apos;{0}&apos; already exists.
        /// </summary>
        internal static string FunctionNameAlreadyExists {
            get {
                return ResourceManager.GetString("FunctionNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the async api url {0} is not valid.
        /// </summary>
        internal static string InvalidAsyncApiUrl {
            get {
                return ResourceManager.GetString("InvalidAsyncApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided JSON input data is invalid.
        /// </summary>
        internal static string InvalidExecutionInput {
            get {
                return ResourceManager.GetString("InvalidExecutionInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the open api url {0} is not valid.
        /// </summary>
        internal static string InvalidOpenApiUrl {
            get {
                return ResourceManager.GetString("InvalidOpenApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation &apos;{0}&apos; already exists.
        /// </summary>
        internal static string OperationExists {
            get {
                return ResourceManager.GetString("OperationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot add api with path &apos;{0}&apos;.
        /// </summary>
        internal static string StandardPath {
            get {
                return ResourceManager.GetString("StandardPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state machine with the same name already exists.
        /// </summary>
        internal static string StateMachineExists {
            get {
                return ResourceManager.GetString("StateMachineExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api &apos;{0}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string UnknownApiDef {
            get {
                return ResourceManager.GetString("UnknownApiDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation &apos;{0}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string UnknownApiDefOperation {
            get {
                return ResourceManager.GetString("UnknownApiDefOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the async api operation {0} doesn&apos;t exist.
        /// </summary>
        internal static string UnknownAsyncApiOperation {
            get {
                return ResourceManager.GetString("UnknownAsyncApiOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the function doesn&apos;t exist.
        /// </summary>
        internal static string UnknownFunction {
            get {
                return ResourceManager.GetString("UnknownFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the open api operation {0} doesn&apos;t exist.
        /// </summary>
        internal static string UnknownOpenApiOperation {
            get {
                return ResourceManager.GetString("UnknownOpenApiOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state machine &apos;{0}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string UnknownStateMachine {
            get {
                return ResourceManager.GetString("UnknownStateMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state machine instance doesn&apos;t exist.
        /// </summary>
        internal static string UnknownStateMachineInstance {
            get {
                return ResourceManager.GetString("UnknownStateMachineInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the function provider is not supported.
        /// </summary>
        internal static string UnsupportedFunctionProvider {
            get {
                return ResourceManager.GetString("UnsupportedFunctionProvider", resourceCulture);
            }
        }
    }
}
