// <auto-generated />
using System;
using FaasNet.EventMesh.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FaasNet.EventMesh.SqlServer.Startup.Migrations
{
    [DbContext(typeof(EventMeshDBContext))]
    partial class EventMeshDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FaasNet.EventMesh.Core.Domains.EventMeshServerAggregate", b =>
                {
                    b.Property<string>("Urn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("CountryIsoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Urn", "Port");

                    b.ToTable("EventMeshServers");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Core.Domains.EventMeshServerBridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EventMeshServerAggregatePort")
                        .HasColumnType("int");

                    b.Property<string>("EventMeshServerAggregateUrn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Urn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventMeshServerAggregateUrn", "EventMeshServerAggregatePort");

                    b.ToTable("EventMeshServerBridge");
                });

            modelBuilder.Entity("FaasNet.EventMesh.Core.Domains.EventMeshServerBridge", b =>
                {
                    b.HasOne("FaasNet.EventMesh.Core.Domains.EventMeshServerAggregate", null)
                        .WithMany("Bridges")
                        .HasForeignKey("EventMeshServerAggregateUrn", "EventMeshServerAggregatePort")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FaasNet.EventMesh.Core.Domains.EventMeshServerAggregate", b =>
                {
                    b.Navigation("Bridges");
                });
#pragma warning restore 612, 618
        }
    }
}
