import { createAction, props } from '@ngrx/store';
import { AppDomainResult } from '../models/appdomain.model';
import { ApplicationResult } from '../models/application.model';
import { ClientResult } from '../models/client.model';
import { MessageDefinitionResult } from '../models/messagedefinition.model';
import { VpnResult } from '../models/vpn.model';

export const startGetAllVpn = createAction('[VPN] START_GET_ALL');
export const completeGetAllVpn = createAction('[VPN] COMPLETE_GET_ALL', props<{ content : VpnResult[] }>());
export const errorGetAllVpn = createAction('[VPN] ERROR_GET_ALL');
export const startAddVpn = createAction('[VPN] START_ADD_VPN', props<{ name: string, description: string }>());
export const completeAddVpn = createAction('[VPN] COMPLETE_ADD_VPN', props<{ name: string, description: string}>());
export const errorAddVpn = createAction('[VPN] ERROR_ADD_VPN');
export const deleteVpn = createAction('[VPN] START_DELETE_VPN', props<{ name: string }>());
export const completeDeleteVpn = createAction('[VPN] COMPLETE_DELETE_VPN', props<{ name: string }>());
export const errorDeleteVpn = createAction('[VPN] ERROR_DELETE_VPN');
export const startGetVpn = createAction('[VPN] START_GET', props<{ name: string }>());
export const completeGetVpn = createAction('[VPN] COMPLETE_GET', props<{ content: VpnResult }>());
export const errorGetVpn = createAction('[VPN] ERROR_GET');
export const startGetAllClients = createAction('[VPN] START_GET_ALL_CLIENTS', props<{ name: string }>());
export const completeGetAllClients = createAction('[VPN] COMPLETE_GET_ALL_CLIENTS', props<{ content: ClientResult[] }>());
export const errorGetAllClients = createAction('[VPN] ERROR_GET_ALL_CLIENTS');
export const startGetClient = createAction('[VPN] START_GET_CLIENT', props<{ name: string, clientId: string }>());
export const completeGetClient = createAction('[VPN] COMPLETE_GET_CLIENT', props<{ content: ClientResult }>());
export const errorGetClient = createAction('[VPN] ERROR_GET_CLIENT');
export const startDeleteClient = createAction('[VPN] START_DELETE_CLIENT', props<{ name: string, clientId: string }>());
export const completeDeleteClient = createAction('[VPN] COMPLETE_DELETE_CLIENT', props<{ name: string, clientId: string }>());
export const errorDeleteClient = createAction('[VPN] ERROR_DELETE_CLIENT');
export const startAddClient = createAction('[VPN] START_ADD_CLIENT', props<{ name: string, clientId: string, purposes : number[] }>());
export const completeAddClient = createAction('[VPN] COMPLETE_ADD_CLIENT', props<{ name: string, clientId: string, purposes: number[] }>());
export const errorAddClient = createAction('[VPN] ERROR_ADD_CLIENT');
export const startGetAppDomain = createAction('[VPN] START_GET_APPDOMAIN', props<{ name: string, appDomainId: string }>());
export const completeGetAppDomain = createAction('[VPN] COMPLETE_GET_APPDOMAIN', props<{ content: AppDomainResult }>());
export const errorGetAppDomain = createAction('[VPN] ERROR_GET_APPDOMAIN');
export const startGetAppDomains = createAction('[VPN] START_GET_APPDOMAINS', props<{ name: string }>());
export const completeGetAppDomains = createAction('[VPN] COMPLETE_GET_APPDOMAINS', props<{ content: AppDomainResult[] }>());
export const errorGetAppDomains = createAction('[VPN] ERROR_GET_APPDOMAINS');
export const startAddAppDomain = createAction('[VPN] START_ADD_APPDOMAIN', props<{ vpn: string, name: string, description: string, rootTopic: string }>());
export const completeAddAppDomain = createAction('[VPN] COMPLETE_ADD_APPDOMAIN', props<{ id: string, name: string, description: string, rootTopic: string }>());
export const errorAddAppDomain = createAction('[VPN] ERROR_ADD_APPDOMAIN');
export const startDeleteAppDomain = createAction('[VPN] START_DELETE_APPDOMAIN', props<{ name: string, appDomainId: string }>());
export const completeDeleteAppDomain = createAction('[VPN] COMPLETE_DELETE_APPDOMAIN', props<{ name: string, appDomainId: string }>());
export const errorDeleteAppDomain = createAction('[VPN] ERROR_DELETE_APPDOMAIN');
export const getLatestMessages = createAction('[VPN] GET_LATEST_MESSAGES', props<{ name: string, appDomainId: string }>());
export const completeGetLatestMessages = createAction('[VPN] COMPLETE_GET_LATEST_MESSAGES', props<{ content : MessageDefinitionResult[] }>());
export const errorGetLatestMessages = createAction('[VPN] ERROR_GET_LATEST_MESSAGES');
export const addMessageDefinition = createAction('[VPN] ADD_MESSAGE_DEFINITION', props<{ vpn: string, applicationDomainId: string, name: string, description: string, jsonSchema: string }>());
export const completeAddMessageDefinition = createAction('[VPN] COMPLETE_ADD_MESSAGE_DEFINITION', props<{ vpn: string, messageDefId: string, applicationDomainId: string, name: string, description: string, jsonSchema: string }>());
export const errorAddMessageDefinition = createAction('[VPN] ERROR_ADD_MESSAGE_DEFINITION');
export const updateMessageDefinition = createAction('[VPN] UPDATE_MESSAGE_DEFINITION', props<{ vpn: string, applicationDomainId: string, messageDefId: string,  description: string, jsonSchema: string }>());
export const completeUpdateMessageDefinition = createAction('[VPN] COMPLETE_UPDATE_MESSAGE_DEFINITION', props<{ vpn: string, applicationDomainId: string, messageDefId: string, description: string, jsonSchema: string }>());
export const errorUpdateMessageDefinition = createAction('[VPN] ERROR_UPDATE_MESSAGE_DEFINITION');
export const publishMessageDefinition = createAction('[VPN] PUBLISH_MESSAGE_DEFINITION', props<{ vpn: string, applicationDomainId: string, messageName: string }>());
export const completePublishMessageDefinition = createAction('[VPN] COMPLETE_PUBLISH_MESSAGE_DEFINITION', props<{ vpn: string, applicationDomainId: string, messageName: string, newMessageDefId: string }>());
export const errorPublishMessageDefinition = createAction('[VPN] ERROR_PUBLISH_MESSAGE_DEFINITION');
export const updateApplicationDomain = createAction('[VPN] UPDATE_APPLICATION_DOMAIN', props<{ vpn: string, applicationDomainId: string, applications: ApplicationResult[] }>());
export const completeUpdateApplicationDomain = createAction('[VPN] COMPLETE_UPDATE_APPLICATION_DOMAIN', props<{ vpn: string, applicationDomainId: string, applications: ApplicationResult[] }>());
export const errorUpdateApplicationDomain = createAction('[VPN] ERROR_UPDATE_APPLICATION_DOMAIN');
