version: '2'
services:
  evtmeshnode1:
    image: 'eventmesh'
    environment:
      EVENTMESH_PLUGIN: "discoveryetcd"
    ports:
      - "4001:4000/udp"
    depends_on:
      - evtmeshnode2
      - etcd
  evtmeshnode2:
    image: 'eventmesh'
    environment:
      EVENTMESH_PLUGIN: "discoveryetcd"
    ports:
      - "4002:4000/udp"
    depends_on:
      - evtmeshnode1
      - etcd
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 23790:2379
      - 23800:2380