# install local opentelemetry collection : https://faun.pub/elastic-apm-and-opentelemetry-integration-49abaaccdad9
# Elasticsearch password must be updated
# ApiKey must be updated.
# Apply the kubernetes file
# Use APM : apm-server-staging-apm-http.faas.svc.cluster.local:8200
# Import the Kibana file
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-external
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 4318
    protocol: TCP
    targetPort: 4318
    nodePort: 30073
  selector:
    component: otel-collector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |-
    receivers:
      otlp:
        protocols:
          http:
    processors:
      batch: null
    exporters:
      otlp/elastic:
        endpoint: 'apm-server-staging-apm-http.faas.svc.cluster.local:8200'
        headers:
          Authorization: "ApiKey enNwTllvQUJfZjlUcWkyT0hrdXU6ZGhqN3JQZWxTZ3V3SUJ5M1BQVHNFZw=="  
        tls:
          insecure: true
      logging:
        loglevel: DEBUG
    extensions:
      health_check:
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [logging, otlp/elastic]
        traces:
          receivers: [otlp]
          exporters: [logging, otlp/elastic]
        logs:
          receivers: [otlp]
          exporters: [logging, otlp/elastic]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib-dev:latest
        ports:
          - containerPort: 4318
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /var/log
          name: varlog
          readOnly: true
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /etc/otel/config.yaml
          name: data
          subPath: config.yaml
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: data
        configMap:
          name: otel-collector-config

---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-staging
spec:
  version: 8.1.3
  count: 1
  http:   
    tls:
      selfSignedCertificate:
        disabled: true
  config:
    apm-server:
      capture_personal_data: true
    instrumentation:
      enabled: true
    output:
      elasticsearch:
        hosts: ["quickstart-es-http.faas.svc.cluster.local:9200"]
        username: elastic
        password: 7o0V9amx965nfwsXD7G2s72L
    logging.level: info
    logging.to_stderr: true
    logging.metrics.enabled: true