# Install https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-kibana.html
apiVersion: v1
kind: Namespace
metadata:
  name: faas
---
kind: Service
apiVersion: v1
metadata:
  name: quickstart-kibana-external
  labels:
    component: elasticsearch
spec:
  type: NodePort
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
  ports:
  - name: 'https'
    protocol: TCP
    port: 5601
    targetPort: 5601
    nodePort: 30072
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.1.3
  count: 1
  elasticsearchRef:
    name: quickstart