import { createAction, props } from '@ngrx/store';
import { PrometheusQueryRangeResult } from '../../common/prometheus-queryrange-result.model';
import { SearchResult } from '../../common/search.model';
import { FunctionResult } from '../models/function.model';

export const startSearch = createAction('[Functions] START_SEARCH_FUNCTIONS', props<{ order: string, direction: string, count: number, startIndex: number }>());
export const completeSearch = createAction('[Functions] COMPLETE_SEARCH_FUNCTIONS', props<{ content: SearchResult<FunctionResult> }>());
export const errorSearch = createAction('[Functions] ERROR_SEARCH_FUNCTIONS');
export const startGetConfiguration = createAction('[Functions] START_GET_FUNCTION_CONFIGURATION', props<{ name: string }>());
export const completeGetConfiguration = createAction('[Functions] COMPLETE_GET_FUNCTION_CONFIGURATION', props<{ content: any }>());
export const errorGetConfiguration = createAction('[Functions] ERROR_GET_FUNCTION_CONFIGURATION');
export const startInvoke = createAction('[Functions] START_INVOKE_FUNCTION', props<{ name: string, request: any }>());
export const completeInvoke = createAction('[Functions] COMPLETE_INVOKE_FUNCTION', props<{ content: any }>());
export const errorInvoke = createAction('[Functions] ERROR_INVOKE_FUNCTION');
export const startGet = createAction('[Functions] START_GET_FUNCTION', props<{ name: string }>());
export const completeGet = createAction('[Functions] COMPLETE_GET_FUNCTION', props<{ content: FunctionResult}>());
export const errorGet = createAction('[Functions] ERROR_GET_FUNCTION');
export const startDelete = createAction('[Functions] START_DELETE_FUNCTION', props<{ name: string }>());
export const completeDelete = createAction('[Functions] COMPLETE_DELETE_FUNCTION');
export const errorDelete = createAction('[Functions] ERROR_DELETE_FUNCTION');
export const startAdd = createAction('[Functions] START_ADD_FUNCTION', props<{ name: string, image: string }>());
export const completeAdd = createAction('[Functions] COMPLETE_ADD_FUNCTION', props<{ name: string, image: string }>());
export const errorAdd = createAction('[Functions] ERROR_ADD_FUNCTION');
export const startGetThreads = createAction("[Functions] START_GET_THREADS", props<{ name: string, startDate: number, endDate: number }>());
export const completeGetThreads = createAction("[Functions] COMPLETE_GET_THREADS", props<{ content: PrometheusQueryRangeResult }>());
export const errorGetThreads = createAction("[Functions] ERROR_GET_THREADS");
export const startGetVirtualMemoryBytes = createAction("[Functions] START_GET_VIRTUAL_MEMORYBYTES", props<{ name: string, startDate: number, endDate: number }>());
export const completeGetVirtualMemoryBytes = createAction("[Functions] COMPLETE_GET_VIRTUAL_MEMORYBYTES", props<{ content: PrometheusQueryRangeResult }>());
export const errorGetVirtualMemoryBytes = createAction("[Functions] ERROR_GET_VIRTUAL_MEMORYBYTES");
