// <auto-generated />
using FaasNet.EventStore.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FaasNet.Application.SqlServer.Startup.Migrations
{
    [DbContext(typeof(EventStoreDBContext))]
    partial class EventStoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FaasNet.EventStore.EF.Models.Snapshot", b =>
                {
                    b.Property<string>("AggregateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<int>("LastEvtOffset")
                        .HasColumnType("int");

                    b.Property<string>("SerializedContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AggregateId", "Version");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("FaasNet.EventStore.EF.Models.Subscription", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TopicName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Offset")
                        .HasColumnType("bigint");

                    b.HasKey("GroupId", "TopicName");

                    b.ToTable("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
