//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaasNet.EventMesh.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FaasNet.EventMesh.Core.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eventmesh server &apos;{0}:{1}&apos; already exists.
        /// </summary>
        internal static string EventMeshServerExists {
            get {
                return ResourceManager.GetString("EventMeshServerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eventmesh server &apos;{0}:{1}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string UnknownEventMeshServer {
            get {
                return ResourceManager.GetString("UnknownEventMeshServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vpn &apos;{0}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string UnknownVpn {
            get {
                return ResourceManager.GetString("UnknownVpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN already exists.
        /// </summary>
        internal static string VpnAlreadyExists {
            get {
                return ResourceManager.GetString("VpnAlreadyExists", resourceCulture);
            }
        }
    }
}
